### PR TITLE
[MM-432] Fix issue of todo getting assigned to last assigned user

### LINKED ISSUE #215: Keeping the assign field empty auto-assigns the ToDo.
If the user has already assigned any ToDo to any other user, then on creating the next ToDo and keeping the assign field empty auto-assigns the ToDo to the last ToDo assigned user.

**Steps to reproduce:-**
1. Create and assign the ToDo to any desired user.
2. Create a new ToDo.
3. Open the assign modal.
4. Keep it empty and click on assign button.

The ToDo would be auto-assigned to the user to whom previous ToDo was assigned.

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary 
- Fixed issue of todo getting assigned to last assigned user
- Can close unifinshed PR https://github.com/mattermost-community/mattermost-plugin-todo/pull/226

#### Ticket Link
- Fixes #215 

#### What to test?
- Assignee field is cleared and the old user is not assigned to the new todo after creating a todo

#### Checklist
- [x] Completed dev testing
- [x] `make test` Ran test cases and ensured they are passing
- [x] `make check-style` Ran style check and ensured both webapp and server pass the checks

### CODE REVIEW

File: webapp/src/components/assignee_modal/assignee_form.jsx [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+
+import AutocompleteSelector from '../user_selector/autocomplete_selector';
+import Button from '../../widget/buttons/button';
+import IconButton from '../../widget/iconButton/iconButton';
+
+import CompassIcon from '../icons/compassIcons';
+
+const AssigneeForm = (
+    {
+        visible,
```
Comment (mickmister) [inline webapp/src/components/assignee_modal/assignee_form.jsx:12]: `visible` will always be `true` in this case, so we can remove this prop

File: webapp/src/components/assignee_modal/assignee_form.jsx [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+                close();
+            }
+        }
+
+        document.addEventListener('keyup', handleKeypress);
+
+        return () => {
+            document.removeEventListener('keyup', handleKeypress);
+        };
+    }, [visible]);
```
Comment (mickmister) [inline webapp/src/components/assignee_modal/assignee_form.jsx:37]: Would be interesting to put this in its own hook for convenience

```ts
const useEscapeKey = (close: () => void) => {
    useEffect(() => {
        function handleKeypress(e) {
            if (e.key === 'Escape') {
                close();
            }
        }

        document.addEventListener('keyup', handleKeypress);

        return () => {
            document.removeEventListener('keyup', handleKeypress);
        };
    }, [close]);
};
```

then in the component

```ts
    useEscapeKey(close);
```

**Review by mickmister — APPROVED** [review]

**Comment by ayusht2810** [comment]
@mickmister Fixed the review fixes. Please re-review.
