### PR TITLE
Fix(Issue#202): counts in one request 

### LINKED ISSUE #202: Combine the webapp plugin's requests for refreshing counts into one request
Currently, the plugin sends a separate HTTP request for each of the categories of counts shown in the left-hand side of the Mattermost UI. THe task here is to instead collect the data for these counts into one API request.

### PR DESCRIPTION
**Pull request by jufab**
#### Summary

I made a counter resource and used it for display counter on the team sidebar.

#### Ticket Link

Fixes #202

### CODE REVIEW

File: webapp/src/actions.js [hunk 1]
```diff
@@ -174,6 +175,26 @@ export const list = (reminder = false, listName = 'my') => async (dispatch, getS
     return {data};
 };
 
+export const count = () => async (dispatch, getState) => {
```
Comment (mickmister) [inline webapp/src/actions.js:178]: I'm thinking this can be a bit more specific. The rest of the functions in this file are mostly one-word verbs, so it may make sense to be consistent with that, but I'm thinking `count` is a bit too vague

```suggestion
export const fetchIssueCounts = () => async (dispatch, getState) => {
```

File: webapp/src/components/sidebar_buttons/sidebar_buttons.jsx [hunk 2]
```diff
@@ -13,11 +13,9 @@ export default class SidebarButtons extends React.PureComponent {
         theme: PropTypes.object.isRequired,
         isTeamSidebar: PropTypes.bool,
         showRHSPlugin: PropTypes.func.isRequired,
-        issues: PropTypes.arrayOf(PropTypes.object),
-        inIssues: PropTypes.arrayOf(PropTypes.object),
-        outIssues: PropTypes.arrayOf(PropTypes.object),
+        countIssues: PropTypes.object,
         actions: PropTypes.shape({
-            list: PropTypes.func.isRequired,
+            count: PropTypes.func.isRequired,
```
Comment (mickmister) [inline webapp/src/components/sidebar_buttons/sidebar_buttons.jsx:18]: It seems that this prop is never used. And the original `list` prop was also not used

File: webapp/src/index.js [hunk 3]
```diff
@@ -66,11 +66,15 @@ export default class Plugin {
             return frontendListName;
         };
 
-        const refresh = ({data: {lists}}) => lists.forEach((listName) => store.dispatch(list(false, getFrontendListName(listName))));
+        const refresh = ({data: {lists}}) => {
```
Comment (mickmister) [inline webapp/src/index.js:69]: Unrelated to this PR, but I would like to make this a bit safer since we're editing this function:

```suggestion
        const refresh = (payload) => {
            if (payload.data && payload.data.lists) {
```

File: webapp/src/index.js [hunk 4]
```diff
@@ -66,11 +66,15 @@ export default class Plugin {
...
+            lists.forEach((listName) => store.dispatch(list(false, getFrontendListName(listName))));
+            store.dispatch(count());
+        };
         const refreshAll = () => {
             store.dispatch(list(false));
             store.dispatch(list(false, 'in'));
             store.dispatch(list(false, 'out'));
+            store.dispatch(count());
```
Comment (mickmister) [inline webapp/src/index.js:77]: I think one of the main purposes of the this PR is to avoid this kind of triple request scenario. Any way we can do just one API call here?

File: webapp/src/index.js [hunk 5]
```diff
@@ -66,11 +66,15 @@ export default class Plugin {
             return frontendListName;
         };
 
-        const refresh = ({data: {lists}}) => lists.forEach((listName) => store.dispatch(list(false, getFrontendListName(listName))));
+        const refresh = ({data: {lists}}) => {
+            lists.forEach((listName) => store.dispatch(list(false, getFrontendListName(listName))));
+            store.dispatch(count());
```
Comment (mickmister) [inline webapp/src/index.js:71]: Ideally we don't have to call this API call here, and instead can provide this data through the websocket event, and not have any API calls here

File: server/plugin.go [hunk 6]
```diff
@@ -340,6 +343,30 @@ func (p *Plugin) handleList(w http.ResponseWriter, r *http.Request) {
...
+	if err != nil {
+		p.API.LogError("Unable to get issues for user err=" + err.Error())
+		p.handleErrorWithCode(w, http.StatusInternalServerError, "Unable to get issues for user", err)
+		return
+	}
+
+	countIssuesJSON, err := json.Marshal(countIssues)
+	if err != nil {
+		p.API.LogError("Unable marhsal count issue list to json err=" + err.Error())
+		p.handleErrorWithCode(w, http.StatusInternalServerError, "Unable marhsal count issue list to json", err)
```
Comment (mickmister) [inline server/plugin.go:359]: Nit: to de-duplicate some string creation here. Same with the block above this one

```suggestion
		msg := "Unable marshal count issue list to json"
		p.API.LogError(msg, "err", err.Error())
		p.handleErrorWithCode(w, http.StatusInternalServerError, msg, err)
```

Comment (mickmister) [reply server/plugin.go:359]: I see now that this is copied from the function above. I'm still thinking we can make this change here

File: server/plugin.go [hunk 7]
```diff
@@ -340,6 +343,30 @@ func (p *Plugin) handleList(w http.ResponseWriter, r *http.Request) {
...
+		return
+	}
+
+	_, err = w.Write(countIssuesJSON)
+	if err != nil {
+		p.API.LogError("Unable to write json response err=" + err.Error())
+	}
+
+}
```
Comment (mickmister) [inline server/plugin.go:368]: Nit: extra newline at the end of this function and `listStore.CountIssues`. This is something we should have the linter configured to enforce, but I'm not sure if we have this particular convention enforced anywhere

File: server/store.go [hunk 8]
```diff
@@ -327,6 +327,28 @@ func (l *listStore) getList(userID, listID string) ([]*IssueRef, []byte, error)
...
+	outList, err := l.GetList(userID, OutListKey)
+	if err != nil {
+		return nil, err
+	}
+
+	return &CountIssue{
+		In:  len(inList),
+		My:  len(myList),
+		Out: len(outList),
+	}, nil
```
Comment (mickmister) [inline server/store.go:348]: Might as well just return the actual lists right? Then the frontend doesn't need to do any other requests

**Review by mickmister — COMMENTED** [review]
Thanks for this improvement @jufab :+1:

I have a few comments and one request to minimize the fetching of lists from the frontend

File: server/plugin.go [hunk 9]
```diff
@@ -32,6 +32,8 @@ type ListManager interface {
 	SendIssue(senderID, receiverID, message, description, postID string) (string, error)
 	// GetIssueList gets the todos on listID for userID
 	GetIssueList(userID, listID string) ([]*ExtendedIssue, error)
+	// CountIssues get counter all issues
```
Comment (raghavaggarwal2308) [inline server/plugin.go:35]:
```suggestion
	// CountIssues get all counter issues
```

File: webapp/src/actions.js [hunk 10]
```diff
@@ -174,6 +175,26 @@ export const list = (reminder = false, listName = 'my') => async (dispatch, getS
...
+    let resp;
+    let data;
+    try {
+        resp = await fetch(getPluginServerRoute(getState()) + '/count', Client4.getOptions({
+            method: 'get',
+        }));
+        data = await resp.json();
```
Comment (raghavaggarwal2308) [inline webapp/src/actions.js:185]:
```suggestion
    let data;
    try {
        const resp = await fetch(getPluginServerRoute(getState()) + '/count', Client4.getOptions({
            method: 'get',
        }));
        data = await resp.json();
```

Comment (raghavaggarwal2308) [reply webapp/src/actions.js:185]: `resp` is not getting reassigned so I think we can make it a const. Also, it's not being used in the outer scope so we can declare it inside the try block.

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by raghavaggarwal2308** [comment]
@jufab Just added a few minor comments, other than that LGTM. You still need to fix the comments provided by @mickmister

File: server/plugin.go (hunk 6 above)
Comment (jufab) [reply server/plugin.go]: I just modified all the error messages the same way

**Comment by jufab** [comment]
Sorry for that but I revised my MR proposal with this single request version for counters and display

File: server/plugin.go (hunk 6 above)
Comment (mickmister) [reply server/plugin.go]: @raghavaggarwal2308 That sounds fine but we would want to change every call to `handleErrorWithCode` as well to avoid double logging. And that's definitely out of scope of this PR

File: server/issue.go [hunk 11]
```diff
@@ -24,6 +24,20 @@ type ExtendedIssue struct {
...
+	My  []*ExtendedIssue `json:"my"`
+	Out []*ExtendedIssue `json:"out"`
+}
+
+// CountIssue for all counter issues
+type CountIssue struct {
+	In  int `json:"in"`
+	My  int `json:"my"`
+	Out int `json:"out"`
+}
```
Comment (mickmister) [inline server/issue.go:39]: This isn't used anywhere anymore so we should remove this type definition

```suggestion
```

File: server/plugin.go [hunk 12]
```diff
@@ -116,6 +118,7 @@ func (p *Plugin) initializeAPI() {
 
 	p.router.HandleFunc("/add", p.checkAuth(p.handleAdd)).Methods(http.MethodPost)
 	p.router.HandleFunc("/list", p.checkAuth(p.handleList)).Methods(http.MethodGet)
```
Comment (mickmister) [inline server/plugin.go:120]: Do we need this endpoint anymore? Or are we still calling this in some cases?

File: server/plugin.go [hunk 13]
```diff
@@ -168,8 +171,9 @@ func (p *Plugin) handleTelemetry(w http.ResponseWriter, r *http.Request) {
 
 	telemetryRequest, err := GetTelemetryPayloadFromJSON(r.Body)
 	if err != nil {
-		p.API.LogError("Unable to get telemetry payload from JSON err=" + err.Error())
-		p.handleErrorWithCode(w, http.StatusBadRequest, "Unable to get telemetry payload from JSON.", err)
+		msg := "Unable to get telemetry payload from JSON"
+		p.API.LogError(msg, "err", err.Error())
+		p.handleErrorWithCode(w, http.StatusBadRequest, msg, err)
```
Comment (mickmister) [inline server/plugin.go:176]: Sorry I was unclear about my request before. We shouldn't edit the log statements in functions unrelated to this PR's purpose. We can clean this up in a separate effort/PR

File: webapp/src/action_types.js [hunk 14]
```diff
@@ -15,6 +15,8 @@ export const REMOVE_ASSIGNEE = pluginId + '_remove_assignee';
 export const GET_ISSUES = pluginId + '_get_issues';
 export const GET_OUT_ISSUES = pluginId + '_get_out_issues';
 export const GET_IN_ISSUES = pluginId + '_get_in_issues';
+export const GET_COUNT_ISSUES = pluginId + '_get_count_issues';
```
Comment (mickmister) [inline webapp/src/action_types.js:18]: This will also be removed

File: webapp/src/actions.js [hunk 15]
```diff
@@ -174,6 +175,25 @@ export const list = (reminder = false, listName = 'my') => async (dispatch, getS
     return {data};
 };
 
+export const fetchAllIssue = () => async (dispatch, getState) => {
```
Comment (mickmister) [inline webapp/src/actions.js:178]:
```suggestion
export const fetchAllIssueLists = () => async (dispatch, getState) => {
```

File: webapp/src/components/sidebar_buttons/index.js [hunk 16]
```diff
@@ -4,27 +4,25 @@
...
+import {fetchAllIssue, updateRhsState, telemetry} from '../../actions';
 
 import SidebarButtons from './sidebar_buttons.jsx';
 
 function mapStateToProps(state) {
     return {
-        issues: state['plugins-com.mattermost.plugin-todo'].issues,
-        inIssues: state['plugins-com.mattermost.plugin-todo'].inIssues,
-        outIssues: state['plugins-com.mattermost.plugin-todo'].outIssues,
+        allIssues: state['plugins-com.mattermost.plugin-todo'].allIssues,
```
Comment (mickmister) [inline webapp/src/components/sidebar_buttons/index.js:13]: I think it makes sense to keep the convention of feeding the component the issues the way we were doing before:

```js
const emptyArray = [];

function mapStateToProps(state) {
    const allIssues = getAllIssues(state); // from selectors.js
    return {
        myIssues: allIssues.my, // note that I changed the prop to be `myIssues`
        inIssues: allIssues.in,
        outIssues: allIssues.out,
```

File: webapp/src/reducer.js [hunk 17]
```diff
@@ -113,6 +114,15 @@ const outIssues = (state = [], action) => {
     }
 };
 
+const allIssues = (state = {}, action) => {
```
Comment (mickmister) [inline webapp/src/reducer.js:117]: Let's handle the undefined state issue here instead of elsewhere

```suggestion
const allIssuesInitialState = {
    my: [],
    in: [],
    out: [],
};

const allIssues = (state = allIssuesInitialState, action) => {
```

File: webapp/src/components/sidebar_right/index.js [hunk 18]
```diff
@@ -4,17 +4,15 @@
...
-import {remove, list, openAssigneeModal, openAddCard, closeAddCard, complete, bump, accept, telemetry, setRhsVisible} from '../../actions';
+import {getSiteURL, getTodoToast} from '../../selectors';
+import {remove, fetchAllIssue, openAssigneeModal, openAddCard, closeAddCard, complete, bump, accept, telemetry, setRhsVisible} from '../../actions';
 
 import SidebarRight from './sidebar_right.jsx';
 
 function mapStateToProps(state) {
     return {
-        todos: getIssues(state),
+        allIssues: state['plugins-com.mattermost.plugin-todo'].allIssues,
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/index.js:14]: We should use the selectors whenever possible. Reading the previous code, I think we can continue using the `getInIssues` etc. selectors to make the consumer code less complicated. The selector would call the `getAllIssues` selector and return `allIssues.in`

Comment (mickmister) [reply webapp/src/components/sidebar_right/index.js:14]: I also like the convention of `myTodos` rather than just `todos`

File: webapp/src/index.js [hunk 19]
```diff
@@ -66,11 +66,11 @@ export default class Plugin {
             return frontendListName;
         };
 
-        const refresh = ({data: {lists}}) => lists.forEach((listName) => store.dispatch(list(false, getFrontendListName(listName))));
+        const refresh = () => {
+            store.dispatch(fetchAllIssue());
```
Comment (mickmister) [inline webapp/src/index.js:70]: Can we have the websocket message that gets sent from the server contain the lists, rather than fetching them here?

File: webapp/src/selectors.js [hunk 20]
```diff
@@ -27,6 +27,7 @@ export const getMessage = (state) => {
 export const getIssues = (state) => getPluginState(state).issues;
 export const getInIssues = (state) => getPluginState(state).inIssues;
 export const getOutIssues = (state) => getPluginState(state).outIssues;
```
Comment (mickmister) [inline webapp/src/selectors.js:29]: These selectors should probably be doing this now:

```suggestion
export const getIssues = (state) => getAllIssues(state).my;
export const getInIssues = (state) => getAllIssues(state).in;
export const getOutIssues = (state) => getAllIssues(state).out;
```

File: webapp/src/components/sidebar_buttons/index.js (hunk 16 above)
Comment (mickmister) [reply webapp/src/components/sidebar_buttons/index.js:13]: Though as mentioned elsewhere, we can use individual selectors for the in issues. The main reason I'm thinking this, is it simplifies what the component needs to worry about

**Review by mickmister — COMMENTED** [review]
Great work on this @jufab. Thanks for addressing the changes :+1:

I have a few more requests on this. There are some conventions that have changed on the frontend to cater towards the new data being transferred, though I think previous component props had a nice separation of concerns. Please let me know your thoughts @jufab

File: server/plugin.go (hunk 12 above)
Comment (jufab) [reply server/plugin.go]: No need so i delete it but getIssueList is used by command

File: server/plugin.go (hunk 13 above)
Comment (jufab) [reply server/plugin.go:175]: Sorry too. should I put everything back the way it was before?

File: webapp/src/action_types.js (hunk 14 above)
Comment (jufab) [reply webapp/src/action_types.js]: Done

File: webapp/src/index.js (hunk 19 above)
Comment (jufab) [reply webapp/src/index.js]: It's after

```
registry.registerWebSocketEventHandler(`custom_${pluginId}_refresh`, refresh);
```

**Comment by jufab** [comment]
I think I resolved all comment 😄

File: server/plugin.go (hunk 13 above)
Comment (mickmister) [reply server/plugin.go:175]: Yes everything that is not related to the main feature/effort of the PR

File: webapp/src/selectors.js [hunk 21]
```diff
@@ -24,9 +24,10 @@ export const getMessage = (state) => {
     }
     return post.message;
 };
-export const getIssues = (state) => getPluginState(state).issues;
-export const getInIssues = (state) => getPluginState(state).inIssues;
-export const getOutIssues = (state) => getPluginState(state).outIssues;
+export const getIssues = (state) => getAllIssues(state).my;
```
Comment (mickmister) [inline webapp/src/selectors.js:27]: Can we rename this to `getMyIssues`?

```suggestion
export const getMyIssues = (state) => getAllIssues(state).my;
```

File: server/plugin.go [hunk 22]
```diff
@@ -290,27 +289,18 @@ func (p *Plugin) postReplyIfNeeded(postID, message, todo string) {
...
+	allListIssue, err := p.listManager.GetAllList(userID)
 	if err != nil {
 		msg := "Unable to get issues for user"
 		p.API.LogError(msg, "err", err.Error())
 		p.handleErrorWithCode(w, http.StatusInternalServerError, msg, err)
 		return
 	}
 
-	if len(issues) > 0 && r.URL.Query().Get("reminder") == "true" && p.getReminderPreference(userID) {
+	if allListIssue != nil && len(allListIssue.My) > 0 && r.URL.Query().Get("reminder") == "true" && p.getReminderPreference(userID) {
```
Comment (mickmister) [inline server/plugin.go:303]: Interesting. I think we are changing the logic here, but I think we are actually fixing a bug. LGTM :+1:

File: server/plugin.go [hunk 23]
```diff
@@ -329,7 +319,7 @@ func (p *Plugin) handleList(w http.ResponseWriter, r *http.Request) {
 		nt := time.Unix(now/1000, 0).In(timezone)
 		lt := time.Unix(lastReminderAt/1000, 0).In(timezone)
 		if nt.Sub(lt).Hours() >= 1 && (nt.Day() != lt.Day() || nt.Month() != lt.Month() || nt.Year() != lt.Year()) {
-			p.PostBotDM(userID, "Daily Reminder:\n\n"+issuesListToString(issues))
+			p.PostBotDM(userID, "Daily Reminder:\n\n"+issuesListToString(allListIssue.My))
```
Comment (mickmister) [inline server/plugin.go:322]: Yeah this is a good bug fix here too. Nice work :+1:

File: webapp/src/components/sidebar_right/sidebar_right.jsx [hunk 24]
```diff
@@ -150,12 +152,12 @@ export default class SidebarRight extends React.PureComponent {
 
         switch (this.state.list) {
         case MyListName:
-            todos = this.props.allIssues.my || [];
+            todos = this.props.myIssues || [];
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/sidebar_right.jsx:155]: These empty arrays are going to cause re-renders. But `this.props.myIssues` should always be defined anyway right? So these actually don't have an effect. Either way I think that this component shouldn't be responsible for this check

File: webapp/src/components/sidebar_right/sidebar_right.jsx [hunk 25]
```diff
@@ -122,15 +124,15 @@ export default class SidebarRight extends React.PureComponent {
     }
 
     getInIssues() {
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/sidebar_right.jsx:126]:
```suggestion
    getInIssuesCount() {
```

It looks like these 3 functions aren't actually called though. I think we can just remove them

File: webapp/src/components/sidebar_right/sidebar_right.jsx [hunk 26]
```diff
@@ -51,7 +51,9 @@ const InListName = 'in';
 
 export default class SidebarRight extends React.PureComponent {
     static propTypes = {
-        allIssues: PropTypes.arrayOf(PropTypes.object),
+        myIssues: PropTypes.array,
```
Comment (mickmister) [inline webapp/src/components/sidebar_right/sidebar_right.jsx:54]:
```suggestion
        myIssues: PropTypes.array.isRequired,
```

Same for the two lines below this one. (GitHub isn't letting me comment on multiple lines for some reason)

image

File: webapp/src/components/sidebar_buttons/sidebar_buttons.jsx [hunk 27]
```diff
@@ -13,7 +13,9 @@ export default class SidebarButtons extends React.PureComponent {
         theme: PropTypes.object.isRequired,
         isTeamSidebar: PropTypes.bool,
         showRHSPlugin: PropTypes.func.isRequired,
-        allIssues: PropTypes.object,
+        myIssues: PropTypes.array,
```
Comment (mickmister) [inline webapp/src/components/sidebar_buttons/sidebar_buttons.jsx:16]: Same here

```suggestion
        myIssues: PropTypes.array.isRequired,
```

File: webapp/src/components/sidebar_buttons/sidebar_buttons.jsx [hunk 28]
```diff
@@ -63,7 +67,7 @@ export default class SidebarButtons extends React.PureComponent {
                         }}
                     >
                         <i className='icon icon-check'/>
-                        {' ' + allIssues && allIssues.my ? allIssues.my.length : 0}
+                        {' ' + myIssues ? myIssues.length : 0}
```
Comment (mickmister) [inline webapp/src/components/sidebar_buttons/sidebar_buttons.jsx:70]: I think `myIssues` will always be defined right?

**Review by mickmister — COMMENTED** [review]
Thanks @jufab! I have just a few more suggestions

File: webapp/src/index.js (hunk 19 above)
Comment (mickmister) [reply webapp/src/index.js]: I'm not sure what this means. Are you saying it's not possible to deliver these changes in the websocket message?

**Comment by mickmister** [comment]
@jufab Is this ready for another review? Just wondering

**Comment by jufab** [comment]
yes ready 😊

File: webapp/src/index.js (hunk 19 above)
Comment (jufab) [reply webapp/src/index.js]: This line is the definition of the function that is then executed in the websocket.

**Comment by jufab** [comment]
Do I have something else to do?

File: server/plugin.go (hunk 13 above)
Comment (mickmister) [reply server/plugin.go:177]: Ideally we do change the logging back the way it was for places unrelated the purpose of the PR, but I don't want to drag this PR on for that reason

**Review by mickmister — APPROVED** [review]
LGTM, thanks @jufab!

**Review by larkox — APPROVED** [review]

**Comment by hanzei** [comment]
Tested locally. No issues found.
